#!/bin/bash

App="Install Failover for OpenHAB"

if [[ $(id -u) -ne 0 ]]; then
  echo "This script must be executed as root or using sudo."
  exit 99
fi

# Eval script dir
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Source main.func for func_check_if_proxmox
source <(curl -s https://raw.githubusercontent.com/BeckenrandschwimmerTim/proxmox/main/misc/main.func)
func_check_if_proxmox

# After func_check_if_proxmox was successfully, continue ...
mkdir -p $DIR/misc
cd $DIR/misc
curl https://raw.githubusercontent.com/BeckenrandschwimmerTim/proxmox/main/misc/main.func -o main.func
source $DIR/misc/main.func

header_info
func_app_title

cd $DIR
curl https://raw.githubusercontent.com/BeckenrandschwimmerTim/proxmox/main/lxc/failover_openhab/failover_openhab_master.sh -o failover_openhab_master.sh
chmod +x failover_openhab_master.sh

cd /etc/systemd/system/
curl https://raw.githubusercontent.com/BeckenrandschwimmerTim/proxmox/main/lxc/failover_openhab/failover_openhab_master.timer -o failover_openhab_master.timer
curl https://raw.githubusercontent.com/BeckenrandschwimmerTim/proxmox/main/lxc/failover_openhab/failover_openhab_master.service -o failover_openhab_master.service

systemctl daemon-reload
systemctl enable --now failover_openhab_master.timer
systemctl status failover_openhab_master.timer
systemctl status failover_openhab_master.service
